/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzarendeles;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author BaksaBence(SZOFT_202
 */
public class Pizzarendeles extends javax.swing.JFrame {

    /**
     * Creates new form Pizzarendeles
     */
    public Pizzarendeles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblfelirat = new javax.swing.JLabel();
        lblmegjegy = new javax.swing.JLabel();
        txtmegjegy = new javax.swing.JTextField();
        lbltel = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        lbllak = new javax.swing.JLabel();
        txtlak = new javax.swing.JTextField();
        lblmenny = new javax.swing.JLabel();
        pnltetszta = new javax.swing.JPanel();
        btnsima = new javax.swing.JRadioButton();
        btnvekony = new javax.swing.JRadioButton();
        btnvastag = new javax.swing.JRadioButton();
        pnlfeltet = new javax.swing.JPanel();
        btnsonka = new javax.swing.JRadioButton();
        btnsajt = new javax.swing.JRadioButton();
        btnkukorica = new javax.swing.JRadioButton();
        pnlszosz = new javax.swing.JPanel();
        btnbarbec = new javax.swing.JRadioButton();
        btnsajtkrem = new javax.swing.JRadioButton();
        btntejszin = new javax.swing.JRadioButton();
        lblweb = new javax.swing.JLabel();
        btnrendeles = new javax.swing.JButton();
        btnmegse = new javax.swing.JButton();
        cmbmenny = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizza rendelés");

        lblfelirat.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 14)); // NOI18N
        lblfelirat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfelirat.setText("Állítsd össze a pizzát!");
        lblfelirat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblmegjegy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmegjegy.setText("Megjegyzés");
        lblmegjegy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblmegjegy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtmegjegy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbltel.setText("Telefonszám:");

        txttel.setText("+36");
        txttel.setToolTipText("");
        txttel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelActionPerformed(evt);
            }
        });

        lbllak.setText("Lakcím:");

        txtlak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlakActionPerformed(evt);
            }
        });

        lblmenny.setText("Mennyiség :");

        pnltetszta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tészta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 0, 14))); // NOI18N

        buttonGroup2.add(btnsima);
        btnsima.setText("Sima");
        btnsima.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnsimaItemStateChanged(evt);
            }
        });

        buttonGroup2.add(btnvekony);
        btnvekony.setText("Vékony");

        buttonGroup2.add(btnvastag);
        btnvastag.setText("Vastag");

        javax.swing.GroupLayout pnltetsztaLayout = new javax.swing.GroupLayout(pnltetszta);
        pnltetszta.setLayout(pnltetsztaLayout);
        pnltetsztaLayout.setHorizontalGroup(
            pnltetsztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltetsztaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnltetsztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnvastag)
                    .addComponent(btnvekony)
                    .addComponent(btnsima))
                .addGap(14, 14, 14))
        );
        pnltetsztaLayout.setVerticalGroup(
            pnltetsztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltetsztaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsima)
                .addGap(18, 18, 18)
                .addComponent(btnvastag)
                .addGap(18, 18, 18)
                .addComponent(btnvekony)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlfeltet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Feltét", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 0, 14))); // NOI18N

        btnsonka.setText("Sonka");
        btnsonka.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnsajt.setText("Sajt");

        btnkukorica.setLabel("Kukorica");

        javax.swing.GroupLayout pnlfeltetLayout = new javax.swing.GroupLayout(pnlfeltet);
        pnlfeltet.setLayout(pnlfeltetLayout);
        pnlfeltetLayout.setHorizontalGroup(
            pnlfeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlfeltetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlfeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsajt)
                    .addComponent(btnsonka)
                    .addComponent(btnkukorica))
                .addContainerGap())
        );
        pnlfeltetLayout.setVerticalGroup(
            pnlfeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlfeltetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsonka)
                .addGap(18, 18, 18)
                .addComponent(btnsajt)
                .addGap(18, 18, 18)
                .addComponent(btnkukorica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlszosz.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Szósz", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 0, 14))); // NOI18N

        buttonGroup1.add(btnbarbec);
        btnbarbec.setLabel("Barbecue");

        buttonGroup1.add(btnsajtkrem);
        btnsajtkrem.setText("Sajtkrémes");

        buttonGroup1.add(btntejszin);
        btntejszin.setLabel("Tejszínes");

        javax.swing.GroupLayout pnlszoszLayout = new javax.swing.GroupLayout(pnlszosz);
        pnlszosz.setLayout(pnlszoszLayout);
        pnlszoszLayout.setHorizontalGroup(
            pnlszoszLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlszoszLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlszoszLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btntejszin)
                    .addComponent(btnbarbec)
                    .addComponent(btnsajtkrem))
                .addContainerGap())
        );
        pnlszoszLayout.setVerticalGroup(
            pnlszoszLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlszoszLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btntejszin)
                .addGap(18, 18, 18)
                .addComponent(btnbarbec)
                .addGap(18, 18, 18)
                .addComponent(btnsajtkrem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblweb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblweb.setText("<html><a href=\"#\">Látogass el oldalunkra!</a></html>"); // NOI18N
        lblweb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblwebMouseClicked(evt);
            }
        });

        btnrendeles.setText("Rendelés");
        btnrendeles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrendelesActionPerformed(evt);
            }
        });

        btnmegse.setText("Mégse");
        btnmegse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmegseActionPerformed(evt);
            }
        });

        cmbmenny.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnltetszta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlfeltet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlszosz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(lblfelirat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblmenny)
                                    .addComponent(lbltel))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbllak)
                                .addGap(36, 36, 36)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtlak)
                            .addComponent(txttel)
                            .addComponent(cmbmenny, 0, 100, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(txtmegjegy, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblmegjegy, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnrendeles)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnmegse, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(lblweb, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblfelirat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnltetszta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlfeltet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlszosz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmenny)
                    .addComponent(cmbmenny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltel)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllak))
                .addGap(26, 26, 26)
                .addComponent(lblmegjegy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmegjegy, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrendeles)
                    .addComponent(btnmegse))
                .addGap(18, 18, 18)
                .addComponent(lblweb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtlakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlakActionPerformed

    private void txttelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelActionPerformed

    private void lblwebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblwebMouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("https://pizzaforte.hu/hu"));
        } catch (IOException ex) {
            Logger.getLogger(Pizzarendeles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblwebMouseClicked

    private void btnmegseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmegseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnmegseActionPerformed

    private void btnrendelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrendelesActionPerformed

        boolean mennyiseg = cmbmenny.getSelectedIndex() < 1 ;
        String uzenet, cim = "FIGYELEM!";
        if(mennyiseg){
            uzenet = "Válassz mennyiséget!";
            int ikontipus = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog(null, uzenet, cim, ikontipus);
            
           
        }
        
     
        else{
            String lakcim = txtlak.getText();
            String telefon = txttel.getText();
            cim = "Köszönjük!";
            String osszeg = "A pizza 2499 Ft-ba kerül!";
            uzenet = "Rendelését felvettük!"+"\n" + lakcim +"\n" + telefon +"\n" + osszeg ;
            int ikontipus = JOptionPane.INFORMATION_MESSAGE;
            JOptionPane.showMessageDialog(null, uzenet, cim, ikontipus);
        }
     
     
    }//GEN-LAST:event_btnrendelesActionPerformed

    private void btnsimaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnsimaItemStateChanged
        String cim = "FIGYELEM!";
        {
        if (btnsima.isSelected())
            cim = "FIGYELEM!";
        String uzenet = "Sima tészta kiválasztva!";
        int ikontipus = JOptionPane.INFORMATION_MESSAGE;
        JOptionPane.showMessageDialog(null, uzenet, cim, ikontipus);
    }
    }//GEN-LAST:event_btnsimaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizzarendeles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnbarbec;
    private javax.swing.JRadioButton btnkukorica;
    private javax.swing.JButton btnmegse;
    private javax.swing.JButton btnrendeles;
    private javax.swing.JRadioButton btnsajt;
    private javax.swing.JRadioButton btnsajtkrem;
    private javax.swing.JRadioButton btnsima;
    private javax.swing.JRadioButton btnsonka;
    private javax.swing.JRadioButton btntejszin;
    private javax.swing.JRadioButton btnvastag;
    private javax.swing.JRadioButton btnvekony;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbmenny;
    private javax.swing.JLabel lblfelirat;
    private javax.swing.JLabel lbllak;
    private javax.swing.JLabel lblmegjegy;
    private javax.swing.JLabel lblmenny;
    private javax.swing.JLabel lbltel;
    private javax.swing.JLabel lblweb;
    private javax.swing.JPanel pnlfeltet;
    private javax.swing.JPanel pnlszosz;
    private javax.swing.JPanel pnltetszta;
    private javax.swing.JTextField txtlak;
    private javax.swing.JTextField txtmegjegy;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
